accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (  login
                                        ,logout
                                        ,password_reset
                                        , password_reset_done
                                        , password_reset_confirm
                                        , password_reset_complete)


urlpatterns = [
    url(r'^login/$' , login , {'template_name' : 'accounts/login.html'} , name='login'),
    url(r'^logout/$' , logout , {'template_name' : 'accounts/logout.html'} , name='logout'),
    url(r'^register/$' , views.register , name='register'),
    url(r'^profile/$' , views.view_profile , name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$' , views.view_profile , name='view_profile_with_pk'),
    url(r'^profile/edit/$' , views.edit_profile , name='edit_profile'),
    url(r'^change-password/$' , views.change_password , name='change_password'),

    url(r'^reset-password/$', password_reset , {'template_name' : 'accounts/reset_password.html' ,
        'post_reset_redirect': 'accounts:password_reset_done' , 'email_template_name' : 'accounts/reset_password_email.html'} , name='password_reset'),

    url(r'^reset-password/done/$' , password_reset_done , {'template_name': 'accounts/reset_password_done.html'} , name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,{'template_name': 'accounts/reset_password_confirm.html' , 'post_reset_redirect' : 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$' , password_reset_complete ,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),


]

data/urls.py
from django.conf.urls import url
from .views import Posts
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^post/$' , Posts.as_view() , name='posts')

]

urlpatterns = format_suffix_patterns(urlpatterns)

tutorial/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from tutorial import  views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.login_redirect , name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/' , include('accounts.urls', namespace= 'accounts')),
    url(r'^home/', include('home.urls' , namespace='home')),
    url(r'^data/' , include('data.urls' , namespace='data'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

#for making queries like filtering ordering easier

class UserProfileManager(models.Manager):

    def get_queryset(self):
        queryset = super(UserProfileManager , self).get_queryset().filter(city='tehran').order_by('user')
        return  queryset

class UserProfile(models.Model):

    user = models.OneToOneField(User)
    description = models.CharField(max_length= 100, default='', null=True ,blank=True)
    city = models.CharField(max_length= 100, default='', null=True ,blank=True)
    website = models.URLField(default='' , null=True , blank=True)
    phone_number = models.IntegerField(default='0', null=True , blank=True)
    image = models.ImageField(upload_to='profile_image' , null=True, blank=True)

    #tehran = UserProfileManager()

    def __str__(self):
        return '{}'.format(self.user)




def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user = kwargs['instance'])
post_save.connect(create_profile , sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm , UserChangeForm





class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password',


        )



    def save(self, commit=True):
        user = super(EditProfileForm , self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user




class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm , self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

accounts/views.py
from django.shortcuts import render , redirect
from .forms import (
    RegistrationForm ,
    EditProfileForm  ,
                    )
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse
from django.contrib.auth.models import User
from .models import UserProfile
from django.forms import inlineformset_factory



def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('home:home'))

    else :
        form = RegistrationForm()
        args = {'form' : form}
        return render(request , 'accounts/reg_form.html' , args)

def view_profile(request , pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user' :user}
    return  render(request , 'accounts/profile.html' , args)



def edit_profile(request):
    #for
    profile_in_line_formset = inlineformset_factory(User, UserProfile, fields=('city',
            'website',
            'phone_number', 'image',))


    if request.method == 'POST':
        form = EditProfileForm(request.POST ,request.FILES, instance=request.user)
        formset = profile_in_line_formset(request.POST ,request.FILES, instance=request.user)
        if form.is_valid():
            edited_user = form.save(commit=False)
            formset = profile_in_line_formset(request.POST ,request.FILES, instance=edited_user)
            if formset.is_valid():
                edited_user.save()
                formset.save()
                return redirect(reverse('accounts:view_profile'))

    else:
        formset = profile_in_line_formset(instance=request.user)
        form = EditProfileForm(instance=request.user)
        args = {'form' : form , 'formset' : formset }
        return render(request , 'accounts/profile_edit.html' , args)




def change_password(request):
    if request.method == 'POST' :
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts: change_password'))

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form' : form}
        return  render(request , 'accounts/change_password.html' , args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h1>change password !</h1>
    <div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">submit</button>
    </form>
    </div>

</div>


{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body  %}
<div class="container">
    <h1>Welcome !</h1>
    <p>
        you can login here !
    </p>
    <h2>login</h2>
    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> login </button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block body  %}
<div class="container">
    <h1>Hope to see you soon</h1>
    <p>
        you have logged out
    </p>
    <h2>logout</h2>
    <form  method="post">
        {% csrf_token %}
    </form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>UserName :  {{user}}</p>
    <p>FirstName :  {{user.first_name}}</p>
    <p>LastName :  {{user.last_name}}</p>
    <p>Email :  {{user.email}}</p>
    <p>City :  {{user.userprofile.city}}</p>
    <p>phone :  {{user.userprofile.phone_number}}</p>
    <p>website :  {{user.userprofile.website}}</p>
    {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" , width="240">
    {%endif%}

</div>


{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h1>Edit Your Profile here</h1>
    <div class="container">
    <form method="post" ,enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.management_form }}
        {{ formset.as_p }}
        <button type="submit">submit</button>
    </form>
    </div>

</div>


{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">submit</button>
    </form>


</div>


{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}
{% block body  %}
<div class="container">
    <h1>Welcome !</h1>
    <p>
        Password reset page
    </p>
    <h2>You can reset your password here !</h2>
    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Reset Password </button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}
{% block body  %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
    Your password has been successfully set ,  You may go ahead and log in now .
    </p>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}
{% block body  %}
<div class="container">
    <h1>Enter new Password</h1>
    <p>
    </p>
    <h2>You can reset your password here !</h2>
    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}
{% block body  %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>


        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}